---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by KraKss.
--- DateTime: 09/06/2023 21:08
---

ESX = exports["es_extended"]:getSharedObject()

pawnshop = {
    pedPos = vector3(218, -866.77, 30.49),
    pedHeading = 251.45,
    pedModel = "a_m_m_salton_02",
    markerPos = vector3(219.45, -867.22, 30.49),
    markerDist = 7,
    openMenuDist = 0.9,
    displayed = false, -- let to false either the menu will never open
    openKey = 38, -- E
    blipData = {
        name = "Marketplace",
        sprite = 617,
        color = 27,
        scale = 0.8,
    },
    payment = "money",
    resellTaxe = 1.21,
    maxItemsPerUser = 10,
}

pawnshop.JSON_PATH  = "storage/data.json"

pawnshop.marker = {
    text = ("Appuyez sur [~b~E~s~] pour accéder au ~b~%s"):format(pawnshop.blipData.name),
    type = 23,
    dirX = 0.0,
    dirY = 0.0,
    dirZ = 0.0,
    rotX = 0.0,
    rotY = 180.0,
    rotZ = 0.0,
    scaleX = 0.7,
    scaleY = 0.7,
    scaleZ = 0.7,
    red = 255,
    green = 255,
    blue = 255,
    alpha = 200,
    bobUpAndDown = false,
    faceCamera = false,
    p19 = 2,
    rotate = nil,
}