---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by KraKss.
--- DateTime: 10/06/2023 00:46
---

function pawnshop:fetchStorage()
    if (not pawnshop.storage) then
        local file <const> = json.decode(LoadResourceFile(GetCurrentResourceName(), pawnshop.JSON_PATH))
        pawnshop.storage = file
    end

    return (pawnshop.storage or {})
end

function pawnshop:updateStorage(newStorage)
    pawnshop.storage = newStorage
end

function pawnshop:getItemAmount(id)
    local file <const> = self:fetchStorage()

    for _,v in pairs(file) do
        if (v.id == id) then
            return (v.amount)
        end
    end

    return (1)
end

function pawnshop:getItemLabel(id)
    local file <const> = self:fetchStorage()

    for _,v in pairs(file) do
        if (v.id == id) then
            return (v.label)
        end
    end

    return ("null")
end

function pawnshop:getItemName(id)
    local file <const> = self:fetchStorage()

    for _,v in pairs(file) do
        if (v.id == id) then
            return (v.name)
        end
    end

    return ("null")
end

function pawnshop:getItemPrice(id)
    local file <const> = self:fetchStorage()

    for _,v in pairs(file) do
        if (v.id == id) then
            return (v.price)
        end
    end

    return (0)
end

function pawnshop:getMoneyFromSell(id, amount)
    local file <const> = self:fetchStorage()

    for _,v in pairs(file) do
        if (v.id == id) then
            return (v.price / self.resellTaxe) * amount
        end
    end

    return (0)
end

function pawnshop:getLastId()
    local file <const> = self:fetchStorage()
    local lastId = 0

    for _,v in pairs(file) do
        if (v.id > lastId) then
            lastId = v.id
        end
    end

    return (lastId)
end

function pawnshop:getSellerLicense(id)
    local file <const> = self:fetchStorage()

    for _,v in pairs(file) do
        if (v.id == id) then
            return (v.license)
        end
    end
end

function pawnshop:constructorItem(name, label, price, amount, description, license)
    local newItem = {
        id = self:getLastId() + 1,
        name = name,
        label = label,
        price = tonumber(("%.0f"):format(price * self.resellTaxe)),
        amount = amount,
        description = description,
        license = license
    }

    return (newItem)
end