---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by KraKss.
--- DateTime: 09/06/2023 23:35
---

RegisterNetEvent("KraKss:pawnshop:updateStorage", function(storage)
    pawnshop:updateStorage(storage)
end)

RegisterNetEvent("KraKss:pawnshop:receiveInSellItems", function(items)
    ---@type table
    pawnshop.playerItemsInSell = items
end)