---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by KraKss.
--- DateTime: 09/06/2023 21:08
---

CreateThread(function()
    while true do
        local sleep = 1000
        local coords = GetEntityCoords(PlayerPedId())

        local dist = #(coords - pawnshop.markerPos)
        if (dist < pawnshop.markerDist) then
            sleep = 0
            DrawMarker(pawnshop.marker.type, pawnshop.markerPos.x, pawnshop.markerPos.y, pawnshop.markerPos.z - 0.99, pawnshop.marker.dirX, pawnshop.marker.dirY, pawnshop.marker.dirZ, pawnshop.marker.rotX, pawnshop.marker.rotY, pawnshop.marker.rotZ, pawnshop.marker.scaleX, pawnshop.marker.scaleY, pawnshop.marker.scaleZ, pawnshop.marker.red, pawnshop.marker.green, pawnshop.marker.blue, pawnshop.marker.alpha, pawnshop.marker.bobUpAndDown, pawnshop.marker.faceCamera, pawnshop.marker.p19, pawnshop.marker.rotate)
            if (dist < pawnshop.openMenuDist) then
                Visual.Subtitle(("%s"):format(pawnshop.marker.text), 0)
                if (IsControlJustPressed(0, pawnshop.openKey)) then
                    pawnshop:openMenu()
                end
            end
        end

        Wait(sleep)
    end
end)

CreateThread(function()
    pawnshop:createBlip()
    pawnshop:createPed()
end)