---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by KraKss.
--- DateTime: 09/06/2023 21:08
---

function pawnshop:openMenu()
    if (self.displayed) then
        return
    end

    self:createMenu()

    RageUI.Visible(self.mainMenu, true)
    self.displayed = true

    CreateThread(function()
        while (self.displayed) do
            SetEntityInvincible(PlayerPedId(), true)
            FreezeEntityPosition(PlayerPedId(), true)

            self:drawMenu()

            if (not RageUI.Visible(self.mainMenu)
                and (not RageUI.Visible(self.buyMenu))
                and (not RageUI.Visible(self.sellMenu))
                and (not RageUI.Visible(self.currentlySellingMenu))) then

                self.displayed = false
                SetEntityInvincible(PlayerPedId(), false)
                FreezeEntityPosition(PlayerPedId(), false)
            end
            Wait(0)
        end
    end)
end